version: '3.0'
services:
    murmur:
        depends_on: 
            - postgres
        image: murmur:1.3.1
        build: .
        ports:
            - "64738:64738/tcp"
            - "64738:64738/udp"
        environment:
            - DATABASE=murmur
            - DB_DRIVER=QPSQL
            - DB_USERNAME=murmur
            - DB_PASSWORD=password
            - DB_HOST=postgres
            - DB_PORT=5432
        restart: unless-stopped
        command: ["/bin/sh", "-c", "wait4ports -s 2 tcp://postgres:5432 && /usr/bin/murmurd -fg -ini /var/lib/murmur/murmur.ini"]
    postgres:
        image: postgres:12-alpine
        ports:
            - 5432:5432
        volumes:
            - murmur:/data
        environment:
            - POSTGRES_USER=murmur
            - POSTGRES_PASSWORD=password
            - PGDATA=/data/postgres

volumes: 
    murmur:
        external: true
